type Query{
  getUser(userId: ID!): User
  allUsers: [User]
  allOwners: [Owner]
   owner(id: ID!): Owner
 
}


type User{
    _id: ID!
    name: String
    address: String
    accountId: String
    googleID: String
    facebookID: String
    email: String
    info: String
    phone: Int
    hashed_password: String
    photo: String
    resetPasswordLink: String
    isVerified: Boolean
    createdAt: String
    updatedAt: String
  }

  type Mutation {
    createUser(userInput: UserInput!): User
    updateUser(userId: ID!, userInput: UserInput!): User
    deleteUser(userId: ID!): Boolean
   
  }
  
  input UserInput {
    name: String
    address: String
    accountId: String
    googleID: String
    facebookID: String
    email: String
    info: String
    phone: Int
    hashed_password: String
    photo: String
    resetPasswordLink: String
    isVerified: Boolean
  }
  type Owner {
    id: ID!
    name: String!
    citizenshipNumber: String!
    phone: Int!
    isVerified: Boolean!
    email: String
    role: String!
  }
  